FROM python:3.11-slim

WORKDIR /app

COPY requirements.web.txt requirements.txt
COPY database /app/database
COPY main_backend.py /app/main_backend.py

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

# Run the application
CMD ["python", "./main_backend.py"]