FROM python:3.11-slim

WORKDIR /app

COPY requirements.web.txt requirements.txt
COPY database /app/database
COPY test.py /app/test.py
COPY templates /app/templates

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

# Run the application
CMD ["python", "./test.py"]