FROM python:3.11-slim

WORKDIR /app

# Update und Installation von curl
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY ../../web-requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ../../database /app/database
COPY ../../src_backend /app/src_backend
COPY ../../.env /app/
COPY ../../main_backend.py /app/

EXPOSE 8000

# Run the application
CMD ["python", "./main_backend.py"]