services:
    backend:
        container_name: backend
        build:
            context: ../..
            dockerfile: ./docker/production/Dockerfile_Backend
        volumes:
            - ../..:/app
        restart: on-failure
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health" ]
            interval: 30s
            timeout: 10s
            retries: 2
        networks:
            - caddy_net

    caddy:
        image: caddy:2
        container_name: caddy
        restart: always
        ports:
            - "127.0.0.1:3000:3000"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
            - ../../web/build:/app/public:ro
        depends_on:
            - backend
        networks:
            - caddy_net

    bot:
        container_name: bot
        build:
            context: ../..
            dockerfile: ./docker/production/Dockerfile_Bot

networks:
    caddy_net:
        driver:
            bridge