services:
    backend:
        container_name: next_gen_backend
        build:
            context: ../..
            dockerfile: ./docker/production/Dockerfile_Backend
        restart: always
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health" ]
            interval: 30s
            timeout: 10s
            retries: 2
        networks:
            - caddy_net
        volumes:
            - ./../../Logs/Backend:/app/Logs/

    caddy:
        image: caddy:2
        container_name: next_gen_caddy
        restart: always
        ports:
            - "127.0.0.1:3000:3000"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
            - ../../web/dist:/app/public:ro
        depends_on:
            - backend
        networks:
            - caddy_net

    bot:
        container_name: next_gen_bot
        restart: always
        build:
            context: ../..
            dockerfile: ./docker/production/Dockerfile_Bot
        volumes:
            - ./../../Logs/Bot:/app/Logs/

networks:
    caddy_net:
        driver:
            bridge
