name: Build and Deploy

on:
  push:
    branches:
      - 'ar-ci-cd'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t frontendForBuild -f docker/development/Dockerfile_Frontend ../..

      - name: Run Build Command inside Docker
        run: |
          docker run frontendForBuild npm run build

