name: Run Flask Tests

on: [ push, pull_request ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3

            -   name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.12'

            -   name: Install Dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r web-requirements.txt

            -   name: Run Tests
                run: |
                    IS_TEST=true python -m unittest discover -s tests
